"""
Debugger and pytest-base for llh2 http/2 frame-parser
for stress testing the llh2 parser
"""


class Parser:
    def reset(self) -> None: ...
    def resume(self) -> None: ...
    def exec(self, obj: object) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def stream_id(self) -> int: ...
    @property
    def type(self) -> int: ...
    @property
    def flags(self) -> int: ...
    @property
    def _sub_length(self) -> int: ...
    @property
    def pad_length(self) -> int: ...
    @property
    def stream_weight(self) -> int: ...
    @property
    def dependency_id(self) -> int: ...
    @property
    def error_code(self) -> int: ...
    @property
    def settings_id(self) -> int: ...
    @property
    def settings_value(self) -> int: ...
    @property
    def promise_stream_id(self) -> int: ...
    @property
    def last_stream_id(self) -> int: ...
    @property
    def window_increment(self) -> int: ...
    @property
    def altsvc_origin_length(self) -> int: ...
    @property
    def is_exclusive(self) -> int: ...

    # Part of Parser if subclassed upon

    def on_body(self, value: bytes) -> int | None: ...
    def altsvc_origin_value(self, value: bytes) -> int | None: ...
    def altsvc_field_value(self, value: bytes) -> int | None: ...
    def on_reset(self) -> int | None: ...
    def on_frame_start(self) -> int | None: ...
    def on_frame_end(self) -> int | None: ...
    def on_length_complete(self) -> int | None: ...
    def on_stream_id_complete(self) -> int | None: ...
    def on_type_complete(self) -> int | None: ...
    def on_flags_complete(self) -> int | None: ...
    def on_body_complete(self) -> int | None: ...
    def on_pad_length_complete(self) -> int | None: ...
    def on_stream_weight_complete(self) -> int | None: ...
    def on_dependency_id_complete(self) -> int | None: ...
    def on_error_code_complete(self) -> int | None: ...
    def on_settings_id(self) -> int | None: ...
    def on_settings_value_complete(self) -> int | None: ...
    def on_promise_stream_id_complete(self) -> int | None: ...
    def on_last_stream_id_complete(self) -> int | None: ...
    def on_window_increment_complete(self) -> int | None: ...
    def on_altsvc_origin_length_complete(self) -> int | None: ...
    def altsvc_origin_value_complete(self) -> int | None: ...
    def altsvc_field_value_complete(self) -> int | None: ...
