name: Test LLH2 C Library
on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  build:
    name: Test on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, windows-11-arm, macos-13, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
        exclude:
          - os: windows-11-arm  # setup-python action only supports 3.11+
            python-version: '3.9'
          - os: windows-11-arm  # setup-python action only supports 3.11+
            python-version: '3.10'
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          check-latest: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        # Time for the change we now want to build a C Library instead of a python wheel...
        run: python -m pip install -r requirements-dev.txt
      - name: Assemble LLH2
        run: python llh2.py
      - name: Cythonize Python Tests & Compile llh2 C Code
        run: python setup_tests.py build_ext --inplace
      - name: Run Pytests
        run: pytest tests -vv
